/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Dynamic queue gradient classes used in QueueList
    'from-blue-500', 'to-violet-500',
    'from-violet-500', 'to-rose-500',
    'from-rose-500', 'to-amber-500',
    'border-l-blue-500/50', 'border-l-violet-500/50', 'border-l-rose-500/50',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Inter"', '"Noto Sans Thai"', 'system-ui', 'sans-serif'],
      },
      colors: {
        brand: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          DEFAULT: '#3b82f6',
          light: '#60a5fa',
          dark: '#1d4ed8',
        },
        surface: {
          900: '#060b18',
          800: '#0a1228',
          700: '#0f1a38',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.4s cubic-bezier(0.16,1,0.3,1) both',
        'fade-in-up': 'fadeInUp 0.5s cubic-bezier(0.16,1,0.3,1) both',
        'slide-up-fade': 'slideUpFade 0.35s cubic-bezier(0.16,1,0.3,1) both',
        'slide-right': 'slideRight 0.35s cubic-bezier(0.16,1,0.3,1) both',
        'scale-in': 'scaleIn 0.3s cubic-bezier(0.34,1.56,0.64,1) both',
        'float': 'float 7s ease-in-out infinite',
        'float-slow': 'float 11s ease-in-out infinite',
        'float-reverse': 'floatReverse 9s ease-in-out infinite',
        'glow-pulse': 'glowPulse 2.8s ease-in-out infinite',
        'spin-slow': 'spin 8s linear infinite',
        'spin-reverse': 'spinReverse 12s linear infinite',
        'eq-1': 'wave 1.0s ease-in-out 0.00s infinite',
        'eq-2': 'wave 1.0s ease-in-out 0.18s infinite',
        'eq-3': 'wave 1.0s ease-in-out 0.35s infinite',
        'eq-4': 'wave 1.0s ease-in-out 0.52s infinite',
        'shimmer': 'shimmer 2.2s ease-in-out infinite',
        'border-flow': 'borderFlow 4s ease-in-out infinite',
        'ping-slow': 'ping 2.5s cubic-bezier(0,0,0.2,1) infinite',
        'heartbeat': 'heartbeat 2s ease-in-out infinite',
        'orb-drift': 'orbDrift 14s ease-in-out infinite',
        'progress-toast': 'progressToast linear forwards',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeInUp: { '0%': { opacity: '0', transform: 'translateY(18px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideUpFade: { '0%': { opacity: '0', transform: 'translateY(12px) scale(0.96)' }, '100%': { opacity: '1', transform: 'translateY(0) scale(1)' } },
        slideRight: { '0%': { opacity: '0', transform: 'translateX(16px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.85)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        float: { '0%,100%': { transform: 'translateY(0px) rotate(0deg)' }, '50%': { transform: 'translateY(-28px) rotate(2deg)' } },
        floatReverse: { '0%,100%': { transform: 'translateY(0px) rotate(0deg)' }, '50%': { transform: 'translateY(28px) rotate(-2deg)' } },
        glowPulse: { '0%,100%': { opacity: '0.5', transform: 'scale(1)' }, '50%': { opacity: '1', transform: 'scale(1.06)' } },
        spinReverse: { to: { transform: 'rotate(-360deg)' } },
        wave: {
          '0%,100%': { height: '4px', opacity: '0.6' },
          '25%': { height: '16px', opacity: '1' },
          '50%': { height: '22px', opacity: '1' },
          '75%': { height: '10px', opacity: '0.8' },
        },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        borderFlow: { '0%,100%': { borderColor: 'rgba(59,130,246,0.50)' }, '33%': { borderColor: 'rgba(139,92,246,0.50)' }, '66%': { borderColor: 'rgba(244,63,94,0.50)' } },
        heartbeat: {
          '0%,100%': { transform: 'scale(1)', opacity: '1' },
          '14%': { transform: 'scale(1.3)', opacity: '1' },
          '28%': { transform: 'scale(1)', opacity: '1' },
          '42%': { transform: 'scale(1.2)', opacity: '1' },
          '70%': { transform: 'scale(1)', opacity: '0.75' },
        },
        orbDrift: {
          '0%,100%': { transform: 'translate(0,0) scale(1)' },
          '33%': { transform: 'translate(30px,-20px) scale(1.05)' },
          '66%': { transform: 'translate(-20px,30px) scale(0.95)' },
        },
        progressToast: {
          '0%': { width: '100%' },
          '100%': { width: '0%' },
        },
      },
      backgroundSize: {
        '200%': '200%',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34,1.56,0.64,1)',
        'smooth': 'cubic-bezier(0.16,1,0.3,1)',
      },
    },
  },
  plugins: [],
}